---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
- name: freebsd-9.2
- name: freebsd-9.2-i386
- name: freebsd-10.0
- name: freebsd-10.1

suites:
- name: portsnap
  run_list: freebsd::portsnap

- name: pkgng
  run_list: freebsd::pkgng
- name: rc_option
  run_list:
  - recipe[rc_option_test::default]
